// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/user/v1/user.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 创建用户所需字段
type CreateUserInfo struct {
	NickName             string   `protobuf:"bytes,1,opt,name=nickName,proto3" json:"nickName,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Mobile               string   `protobuf:"bytes,3,opt,name=mobile,proto3" json:"mobile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserInfo) Reset()         { *m = CreateUserInfo{} }
func (m *CreateUserInfo) String() string { return proto.CompactTextString(m) }
func (*CreateUserInfo) ProtoMessage()    {}
func (*CreateUserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_68a8f9c10c733b91, []int{0}
}

func (m *CreateUserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserInfo.Unmarshal(m, b)
}
func (m *CreateUserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserInfo.Marshal(b, m, deterministic)
}
func (m *CreateUserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserInfo.Merge(m, src)
}
func (m *CreateUserInfo) XXX_Size() int {
	return xxx_messageInfo_CreateUserInfo.Size(m)
}
func (m *CreateUserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserInfo proto.InternalMessageInfo

func (m *CreateUserInfo) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *CreateUserInfo) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CreateUserInfo) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

// 返回用户信息
type UserInfoResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Mobile               string   `protobuf:"bytes,3,opt,name=mobile,proto3" json:"mobile,omitempty"`
	NickName             string   `protobuf:"bytes,4,opt,name=nickName,proto3" json:"nickName,omitempty"`
	Birthday             int64    `protobuf:"varint,5,opt,name=birthday,proto3" json:"birthday,omitempty"`
	Gender               string   `protobuf:"bytes,6,opt,name=gender,proto3" json:"gender,omitempty"`
	Role                 int32    `protobuf:"varint,7,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfoResponse) Reset()         { *m = UserInfoResponse{} }
func (m *UserInfoResponse) String() string { return proto.CompactTextString(m) }
func (*UserInfoResponse) ProtoMessage()    {}
func (*UserInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_68a8f9c10c733b91, []int{1}
}

func (m *UserInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoResponse.Unmarshal(m, b)
}
func (m *UserInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoResponse.Marshal(b, m, deterministic)
}
func (m *UserInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoResponse.Merge(m, src)
}
func (m *UserInfoResponse) XXX_Size() int {
	return xxx_messageInfo_UserInfoResponse.Size(m)
}
func (m *UserInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoResponse proto.InternalMessageInfo

func (m *UserInfoResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserInfoResponse) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UserInfoResponse) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *UserInfoResponse) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *UserInfoResponse) GetBirthday() int64 {
	if m != nil {
		return m.Birthday
	}
	return 0
}

func (m *UserInfoResponse) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *UserInfoResponse) GetRole() int32 {
	if m != nil {
		return m.Role
	}
	return 0
}

func init() {
	proto.RegisterType((*CreateUserInfo)(nil), "api.user.v1.CreateUserInfo")
	proto.RegisterType((*UserInfoResponse)(nil), "api.user.v1.UserInfoResponse")
}

func init() { proto.RegisterFile("api/user/v1/user.proto", fileDescriptor_68a8f9c10c733b91) }

var fileDescriptor_68a8f9c10c733b91 = []byte{
	// 251 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4b, 0x2c, 0xc8, 0xd4,
	0x2f, 0x2d, 0x4e, 0x2d, 0xd2, 0x2f, 0x33, 0x04, 0xd3, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42,
	0xdc, 0x89, 0x05, 0x99, 0x7a, 0x60, 0x7e, 0x99, 0xa1, 0x52, 0x02, 0x17, 0x9f, 0x73, 0x51, 0x6a,
	0x62, 0x49, 0x6a, 0x68, 0x71, 0x6a, 0x91, 0x67, 0x5e, 0x5a, 0xbe, 0x90, 0x14, 0x17, 0x47, 0x5e,
	0x66, 0x72, 0xb6, 0x5f, 0x62, 0x6e, 0xaa, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x9c, 0x0f,
	0x92, 0x2b, 0x48, 0x2c, 0x2e, 0x2e, 0xcf, 0x2f, 0x4a, 0x91, 0x60, 0x82, 0xc8, 0xc1, 0xf8, 0x42,
	0x62, 0x5c, 0x6c, 0xb9, 0xf9, 0x49, 0x99, 0x39, 0xa9, 0x12, 0xcc, 0x60, 0x19, 0x28, 0x4f, 0x69,
	0x17, 0x23, 0x97, 0x00, 0xcc, 0xf0, 0xa0, 0xd4, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x21, 0x3e,
	0x2e, 0xa6, 0xcc, 0x14, 0xb0, 0xf1, 0xcc, 0x41, 0x4c, 0x99, 0x29, 0xe4, 0x18, 0x8c, 0xe2, 0x50,
	0x16, 0x4c, 0x87, 0x26, 0x65, 0x16, 0x95, 0x64, 0xa4, 0x24, 0x56, 0x4a, 0xb0, 0x82, 0x6d, 0x81,
	0xf3, 0x41, 0xe6, 0xa5, 0xa7, 0xe6, 0xa5, 0xa4, 0x16, 0x49, 0xb0, 0x41, 0xcc, 0x83, 0xf0, 0x84,
	0x84, 0xb8, 0x58, 0x8a, 0xf2, 0x73, 0x52, 0x25, 0xd8, 0x15, 0x18, 0x35, 0x58, 0x83, 0xc0, 0x6c,
	0xa3, 0x00, 0x2e, 0x16, 0x90, 0xdb, 0x85, 0x3c, 0xb8, 0xb8, 0x10, 0xc1, 0x24, 0x24, 0xad, 0x87,
	0x14, 0x84, 0x7a, 0xa8, 0xe1, 0x27, 0x25, 0x8b, 0x22, 0x89, 0xee, 0x73, 0x27, 0xd1, 0x28, 0x61,
	0x70, 0x9c, 0x20, 0x45, 0x8e, 0x75, 0x99, 0x61, 0x12, 0x1b, 0x38, 0x6e, 0x8c, 0x01, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x70, 0x7a, 0x1f, 0x2f, 0xb5, 0x01, 0x00, 0x00,
}
