components:
  schemas:
    GoodsV1AttrGroupRequest:
      properties:
        desc:
          type: string
        id:
          format: int64
          type: integer
        sort:
          format: int32
          type: integer
        status:
          type: boolean
        title:
          type: string
        typeId:
          format: int64
          type: integer
      type: object
    GoodsV1AttrGroupResponse:
      properties:
        desc:
          type: string
        id:
          format: int64
          type: integer
        sort:
          format: int32
          type: integer
        status:
          type: boolean
        title:
          type: string
        typeId:
          format: int64
          type: integer
      type: object
    GoodsV1AttrResponse:
      properties:
        attrValue:
          items:
            $ref: '#/components/schemas/GoodsV1AttrValueResponse'
          type: array
        desc:
          type: string
        groupId:
          format: int64
          type: integer
        id:
          format: int64
          type: integer
        sort:
          format: int32
          type: integer
        status:
          type: boolean
        title:
          type: string
        typeId:
          format: int64
          type: integer
      type: object
    GoodsV1AttrValueRequest:
      properties:
        attrId:
          format: int64
          type: integer
        groupId:
          format: int64
          type: integer
        id:
          format: int64
          type: integer
        value:
          type: string
      type: object
    GoodsV1AttrValueResponse:
      properties:
        attrId:
          format: int64
          type: integer
        groupId:
          format: int64
          type: integer
        id:
          format: int64
          type: integer
        value:
          type: string
      type: object
    GoodsV1CategoryInfoRequest:
      properties:
        id:
          format: int32
          type: integer
        isTab:
          type: boolean
        level:
          format: int32
          type: integer
        name:
          type: string
        parentCategory:
          format: int32
          type: integer
        sort:
          format: int32
          type: integer
      type: object
    GoodsV1CategoryInfoResponse:
      properties:
        id:
          format: int32
          type: integer
        isTab:
          type: boolean
        level:
          format: int32
          type: integer
        name:
          type: string
        parentCategory:
          format: int32
          type: integer
        sort:
          format: int32
          type: integer
      type: object
    GoodsV1CreateGoodsRequest:
      properties:
        brandId:
          format: int32
          type: integer
        categoryId:
          format: int32
          type: integer
        goodsBrief:
          type: string
        goodsFrontImage:
          type: string
        goodsImages:
          items:
            type: string
          type: array
        goodsSn:
          type: string
        goodsTags:
          type: string
        id:
          format: int64
          type: integer
        inventory:
          format: int64
          type: integer
        isHot:
          type: boolean
        isNew:
          type: boolean
        marketPrice:
          format: int64
          type: integer
        name:
          type: string
        nameAlias:
          type: string
        onSale:
          type: boolean
        shipFree:
          type: boolean
        shipId:
          format: int32
          type: integer
        shopPrice:
          format: int64
          type: integer
        sku:
          items:
            $ref: '#/components/schemas/GoodsV1CreateGoodsRequestGoodsSku'
          type: array
        typeId:
          format: int64
          type: integer
      type: object
    GoodsV1CreateGoodsResponse:
      properties:
        ID:
          format: int64
          type: integer
      type: object
    GoodsV1GoodsFilterRequest:
      properties:
        brandId:
          format: int32
          type: integer
        categoryId:
          format: int32
          type: integer
        clickNum:
          format: int64
          type: integer
        favNum:
          format: int64
          type: integer
        id:
          format: int64
          type: integer
        isHot:
          type: boolean
        isNew:
          type: boolean
        isTab:
          type: boolean
        keywords:
          type: string
        maxPrice:
          format: int64
          type: integer
        minPrice:
          format: int64
          type: integer
        pagePerNums:
          format: int64
          type: integer
        pages:
          format: int64
          type: integer
        soldNum:
          format: int64
          type: integer
      type: object
    GoodsV1GoodsInfoResponse:
      properties:
        brandId:
          format: int32
          type: integer
        categoryId:
          format: int32
          type: integer
        clickNum:
          format: int64
          type: integer
        favNum:
          format: int64
          type: integer
        goodsBrief:
          type: string
        goodsDesc:
          type: string
        goodsImages:
          items:
            type: string
          type: array
        goodsSn:
          type: string
        id:
          format: int64
          type: integer
        images:
          type: string
        isHot:
          type: boolean
        isNew:
          type: boolean
        marketPrice:
          format: int64
          type: integer
        name:
          type: string
        onSale:
          type: boolean
        shipFree:
          type: boolean
        soldNum:
          format: int64
          type: integer
      type: object
    GoodsV1GoodsListResponse:
      properties:
        list:
          items:
            $ref: '#/components/schemas/GoodsV1GoodsInfoResponse'
          type: array
        total:
          format: int64
          type: integer
      type: object
    GoodsV1GoodsTypeRequest:
      properties:
        desc:
          type: string
        id:
          format: int64
          type: integer
        isVirtual:
          type: boolean
        name:
          type: string
        nameAlias:
          type: string
        sort:
          format: int32
          type: integer
        typeCode:
          type: string
      type: object
    GoodsV1GoodsTypeResponse:
      properties:
        id:
          format: int64
          type: integer
      type: object
    GoodsV1SpecificationRequest:
      properties:
        id:
          format: int64
          type: integer
        isSelect:
          type: boolean
        isSku:
          type: boolean
        name:
          type: string
        sort:
          format: int32
          type: integer
        specificationValue:
          items:
            $ref: '#/components/schemas/GoodsV1SpecificationValue'
          type: array
        status:
          type: boolean
        typeId:
          format: int64
          type: integer
      type: object
    GoodsV1SpecificationResponse:
      properties:
        id:
          format: int64
          type: integer
      type: object
    GoodsV1SpecificationValue:
      properties:
        attrId:
          format: int64
          type: integer
        id:
          format: int64
          type: integer
        sort:
          format: int32
          type: integer
        value:
          type: string
      type: object
info:
  description: goods.v1
  title: goods.v1
  version: "1"
openapi: 3.0.0
paths:
  /goods.v1.Goods/CreateAttrGroup:
    description: 商品参数属性分组名
    post:
      description: 商品参数属性分组名
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GoodsV1AttrGroupRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GoodsV1AttrGroupResponse'
          description: ok
      summary: 商品参数属性分组名
      tags:
      - goods.v1.Goods
    summary: CreateAttrGroup
  /goods.v1.Goods/CreateAttrValue:
    description: 商品参数属性名和值
    post:
      description: 商品参数属性名和值
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GoodsV1AttrValueRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GoodsV1AttrResponse'
          description: ok
      summary: 商品参数属性名和值
      tags:
      - goods.v1.Goods
    summary: CreateAttrValue
  /goods.v1.Goods/CreateCategory:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GoodsV1CategoryInfoRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GoodsV1CategoryInfoResponse'
          description: ok
      tags:
      - goods.v1.Goods
    summary: CreateCategory
  /goods.v1.Goods/CreateGoods:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GoodsV1CreateGoodsRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GoodsV1CreateGoodsResponse'
          description: ok
      tags:
      - goods.v1.Goods
    summary: CreateGoods
  /goods.v1.Goods/CreateGoodsSpecification:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GoodsV1SpecificationRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GoodsV1SpecificationResponse'
          description: ok
      tags:
      - goods.v1.Goods
    summary: CreateGoodsSpecification
  /goods.v1.Goods/CreateGoodsType:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GoodsV1GoodsTypeRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GoodsV1GoodsTypeResponse'
          description: ok
      tags:
      - goods.v1.Goods
    summary: CreateGoodsType
  /goods.v1.Goods/GoodsList:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GoodsV1GoodsFilterRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GoodsV1GoodsListResponse'
          description: ok
      tags:
      - goods.v1.Goods
    summary: GoodsList
tags:
- name: goods.v1.Goods

