version: '3'
services:
  shopdb:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: dangerous
      MYSQL_DATABASE: shop_user
    ports:
      - 3308:3306
    volumes:
      - "./data:/var/lib/mysql"

  consul:
    image: consul
    command: agent -dev -client=0.0.0.0
    ports:
      - 8500:8500   
      - 8300:8300 
      - 8301:8301 
      - 8600:8600/udp 
  
  shopredis:
    image: redis 
    ports:
      - 6380:6379   
  
  jaeger:
    image: jaegertracing/all-in-one 
    ports:
      - 14268:14268  
      - 16686:16686 
