version: '3'
services:
  shopdb:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: dangerous
      MYSQL_DATABASE: shop_user
    ports:
      - 3308:3306
    volumes:
      - "./data:/var/lib/mysql"

  consul:
    image: consul
    command: agent -dev -client=0.0.0.0
    ports:
      - 8500:8500   
      - 8300:8300 
      - 8301:8301 
      - 8600:8600/udp 
  
  shopredis:
    image: redis 
    ports:
      - 6380:6379   
  
  jaeger:
    image: jaegertracing/all-in-one 
    ports:
      - 14268:14268  
      - 16686:16686 
  elasticsearch:
    image: elasticsearch:7.16.3
    environment:
        - discovery.type=single-node
        - ES_JAVA_OPTS=-Xms64m -Xmx128m
    ports:
        - "9200:9200"
        - "9300:9300"    
    volumes:
        - /etc/localtime:/etc/localtime
        - ./elasticsearch/data:/usr/share/elasticsearch/data
        - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
        - ./elasticsearch/plugins:/usr/share/elasticsearch/plugins
  kibana:
    depends_on:
        - elasticsearch
    image: kibana:7.16.3
    environment:
        - ELASTICSEARCH_URL=http://elasticsearch:9200
    volumes:
        - /etc/localtime:/etc/localtime
    ports:
        - "5601:5601"    
    links:
        - elasticsearch