version: '3'
services:
  rwdb:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: dangerous
      MYSQL_DATABASE: shop_user
    ports:
      - 3308:3306
    volumes:
      - "./data:/var/lib/mysql"